# addoninfo writer: turns workshop metadata into a cs2 addon's
# addoninfo.gi / addoninfo.json + thumbnail.
#
# we DO NOT clobber a user-authored addoninfo if one already exists --
# the user may have edited it after the import, and overwriting is the
# kind of silent-data-loss the rest of the tool is careful to avoid. we
# only write when the addon dir has no addoninfo at all, or the file is
# empty/auto-populated by us (we mark our writes with a `_csgo2cs2`
# sentinel field).

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Optional

from .workshop_meta import WorkshopMetadata

# sentinel field we write into auto-populated addoninfo so future runs
# can tell "this was generated by us; safe to overwrite" from "the user
# edited this; leave it alone".
SENTINEL_KEY = "_csgo2cs2"
SENTINEL_VALUE = "auto-populated from workshop metadata"

# preferred output filename. cs2's loader accepts .gi (keyvalues) and
# .json (json). we go with .json because it's easier to parse + verify
# and matches the existing verify_cmd code path.
DEFAULT_FILENAME = "addoninfo.json"

# cs2's addon thumbnail file. lives at the addon root and is shown in
# workshop tools / cs2's addons list. .jpg is preferred; cs2 also accepts
# .png but the workshop preview is jpg in 99% of cases.
THUMBNAIL_FILENAMES = ("addonimage.jpg", "addonimage.png")


def _existing_addoninfo(addon_dir: Path) -> Optional[Path]:
    for name in ("addoninfo.gi", "addoninfo.json", "addoninfo.txt"):
        p = addon_dir / name
        if p.exists():
            return p
    return None


def _was_auto_populated(addoninfo: Path) -> bool:
    if addoninfo.suffix != ".json":
        return False
    try:
        data = json.loads(addoninfo.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    if not isinstance(data, dict):
        return False
    return data.get(SENTINEL_KEY) == SENTINEL_VALUE


# build the addoninfo dict from workshop metadata. we keep field names
# in the conservative shape valve's loader accepts; extra fields are
# ignored by cs2 but useful as a manifest of where the data came from.
def build_addoninfo(meta: WorkshopMetadata) -> dict:
    return {
        SENTINEL_KEY: SENTINEL_VALUE,
        "title": meta.title or f"Workshop {meta.workshop_id}",
        "description": meta.description or "",
        "tags": list(meta.tags),
        "workshop_id": str(meta.workshop_id),
        "creator": meta.creator or "",
        "time_created": meta.time_created or 0,
        "time_updated": meta.time_updated or 0,
    }


# write addoninfo.json under addon_dir from the supplied metadata.
# returns the path written, or None if a user-authored addoninfo
# already exists (we leave it alone). force=True overrides that check.
def write_addoninfo(
    meta: WorkshopMetadata,
    addon_dir: Path,
    *,
    force: bool = False,
) -> Optional[Path]:
    addon_dir = addon_dir.expanduser()
    addon_dir.mkdir(parents=True, exist_ok=True)

    existing = _existing_addoninfo(addon_dir)
    if existing is not None and not force and not _was_auto_populated(existing):
        # user-authored: don't clobber
        return None

    target = addon_dir / DEFAULT_FILENAME
    payload = build_addoninfo(meta)
    target.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # if the existing addoninfo was a different filename (.gi / .txt) and
    # was an auto-populated one, drop it so we don't end up with two.
    if existing is not None and existing != target and _was_auto_populated(existing):
        try:
            existing.unlink()
        except OSError:
            pass

    return target


# copy the workshop preview into addonimage.jpg/.png at addon root.
# returns the path written, or None if no preview was downloaded.
def copy_thumbnail(
    preview_path: Optional[Path],
    addon_dir: Path,
    *,
    force: bool = False,
) -> Optional[Path]:
    if preview_path is None:
        return None
    if not preview_path.exists():
        return None
    addon_dir = addon_dir.expanduser()
    addon_dir.mkdir(parents=True, exist_ok=True)

    suffix = preview_path.suffix.lower()
    if suffix not in {".jpg", ".jpeg", ".png"}:
        # unknown image type; default to .jpg since that's what steam
        # serves overwhelmingly
        suffix = ".jpg"
    target_name = "addonimage.jpg" if suffix in {".jpg", ".jpeg"} else "addonimage.png"
    target = addon_dir / target_name

    # skip if a same-named non-empty image already exists -- the user
    # may have replaced it with a custom thumbnail post-port.
    if target.exists() and target.stat().st_size > 0 and not force:
        return None

    shutil.copyfile(preview_path, target)
    return target
